name: obrikosovo
version: '1.1-SNAPSHOT'
main: ru.moose23967.obrikosovo.Obrikosovo
api-version: '1.20'
commands:
  enderchest:
    description: Open player's ender chest
    usage: /enderchest
  respawn:
    description: Teleport player to respawn location
    usage: /respawn
  spawn:
    description: Teleport player to spawn location
    usage: /spawn
